name: Scala CI

on:
  push:
    branches:
      - feature-abstraccion

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: hseeberger/scala-sbt:8u302_1.5.5_2.13.6
      options: --user root  # Este es un truco para evitar problemas de permisos

    steps:
    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-

    - name: Run tests
      run: |
        # Ejecuta los tests y guarda la salida en un archivo temporal
        sbt test > test-output.txt 2>&1

        # Verifica si los tests pasaron o fallaron
        if grep -q 'Tests failed' test-output.txt; then
          echo "Tests failed"
          # Agrega aquí el código para crear el issue en GitHub
        else
          echo "Tests passed"
        fi
