name: Scala CI

on:
  push:
    branches:
      - feature-abstraccion

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: hseeberger/scala-sbt:8u302_1.5.5_2.13.6
      options: --user root  # Este es un truco para evitar problemas de permisos

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ./temas/abstraccion/scala/proyecto

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-

    - name: Run tests
      run: |
        cd ./temas/abstraccion/scala/proyecto
        sbt test > test-output.txt 2>&1

        # Captura el código de salida del comando sbt test
        TEST_EXIT_CODE=$?

        # Verifica si los tests pasaron o fallaron
        if [ $TEST_EXIT_CODE -ne 0 ]; then
          echo "Tests failed"
          # Agrega aquí el código para crear el issue en GitHub
        else
          echo "Tests passed"
        fi
      shell: bash
