name: Scala CI

on:
  push:
    branches:
      - feature-abstraccion

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: hseeberger/scala-sbt:8u302_1.5.5_2.13.6
      options: --user root

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: ./temas/abstraccion/scala/proyecto

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.cache/coursier
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt', '**/*.scala') }}
        restore-keys: |
          ${{ runner.os }}-sbt-

    - name: List project files
      run: |
        cd ./temas/abstraccion/scala/proyecto
        ls -la
      
    - name: Run tests with verbose logging
      with:
        path: ./temas/abstraccion/scala/proyecto
      run: 
        sbt 'set logLevel in Test := Level.Debug' test

