name: Scala CI

on:
  push:
    branches:
      - feature-abstraccion

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: hseeberger/scala-sbt:8u302_1.5.5_2.13.6
      options: --user root  # Este es un truco para evitar problemas de permisos

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ./temas/abstraccion/scala/proyecto

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-

    - name: Run tests
      run: |
        cd ./temas/abstraccion/scala/proyecto
        
        # Ejecuta `sbt test` y guarda la salida en la variable `test_output`
        test_output=$(sbt test)
        echo "$test_output" # Esta línea es opcional y solo para depurar
        
        # Verifica si hubo errores en la salida de sbt test
        if echo "$test_output" | grep -q 'FAILED'; then
          echo "Tests failed"
          exit 1  # Cambia el estado a fallido para que GitHub Actions lo refleje
        else
          echo "All tests passed"
        fi
