# Tu archivo de flujo de trabajo de GitHub Actions

name: Scala CI

on:
  push:
    branches:
      - feature-abstraccion

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: hseeberger/scala-sbt:8u302_1.5.5_2.13.6
      options: --user root  # Este es un truco para evitar problemas de permisos

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ./temas/abstraccion/scala/proyecto

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-

    - name: Run tests
      run: |
        cd ./temas/abstraccion/scala/proyecto
        
        # Ejecuta `sbt test` directamente sin entrar en la interfaz interactiva
        test_output=$(sbt test 2>&1)
        
        # Verifica si hubo errores en la salida de sbt test
        if echo "$test_output" | grep -q 'TESTS FAILED\|TEST FAILED'; then
          echo "Tests failed"
          # Agrega aquí el código para crear el issue en GitHub
        else
          echo "Tests passed"
        fi
