name: Scala CI

on:
  push:
    branches:
      - feature-abstraccion

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' # AdoptOpenJDK, ahora conocido como Eclipse Temurin

    - name: Cache Scala and SBT files
      uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.cache/coursier
          ~/.m2
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-java-17
        restore-keys: |
          ${{ runner.os }}-sbt-java-17

    - name: Execute sbt clean and compile
      run: sbt clean compile

    - name: Execute tests
      run: sbt test