name: Deploy Website

on:
  push:
    branches:
      - feat-herencia
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - name: Install dependencies
      run: gem install nokogiri

    - name: Run Ruby script
      run: ruby ./temas/herencia/ruby/Students.rb

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./temas/herencia/ruby/Students.rb
