name: Kotlin CI Test

on:
  push:
    branches:
      - feature-errores
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'

    - name: install gradle
      run: |
        sudo apt-get update
        sudo apt-get install -y gradle

    - name: Build and Test with Gradle
      run: |
        ./gradle build
        ./gradle test
