name: Ruby Sinatra CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true

    - name: Install Bundler 2.4.22
      run: gem install bundler -v 2.4.22

    - name: Create Gemfile
      run: |
        echo "source 'https://rubygems.org'" > Gemfile
        echo "ruby '3.0.0'" >> Gemfile
        echo "gem 'sinatra'" >> Gemfile
        echo "gem 'rspec'" >> Gemfile
        echo "gem 'rake'" >> Gemfile
        echo "gem 'rackup'" >> Gemfile
      

    - name: Install dependencies
      run: |
        cat Gemfile
        bundle install

    - name: Run tests
      run: |
        bundle exec rspec 
      
    - name: Start Sinatra server
      run: |
        bundle exec ruby ./temas/delegacion/ruby/ShoppingCart.rb &

    - name: Start ngrok
      uses: wadewegner/ngrok-action@master
      with:
        authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Get ngrok URL
      id: ngrok
      run: echo "::set-output name=url::$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"

    - name: Display ngrok URL
      run: |
        echo "Ngrok URL: ${{ steps.ngrok.outputs.url }}"

      
