name: Ruby Sinatra CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - name: Install Bundler 2.4.22
      run: gem install bundler -v 2.4.22

    - name: Create Gemfile
      run: echo "ruby '3.0.0'\ngem 'sinatra'" > Gemfile

    - name: Install dependencies
      run: |
        bundle config set path 'vendor/bundle'

    - name: Run tests
      run: |
        bundle exec rspec 

    - name: Build
      run: |
        bundle exec rake build
