name: Ruby Sinatra CI

on:
  push:
    branches:
      - feat-delegacion

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true

    - name: Install Bundler 2.4.22
      run: gem install bundler -v 2.4.22

    - name: Create Gemfile
      run: |
        echo "source 'https://rubygems.org'" > Gemfile
        echo "ruby '3.0.0'" >> Gemfile
        echo "gem 'sinatra'" >> Gemfile
        echo "gem 'rspec'" >> Gemfile
        echo "gem 'rake'" >> Gemfile
        echo "gem 'rackup'" >> Gemfile
      

    - name: Install dependencies
      run: |
        cat Gemfile
        bundle install

    - name: Run tests
      run: |
        bundle exec rspec 
      
    - name: Start Server
      run: |
        bundle exec ruby ./temas/delegacion/ruby/ShoppingCart.rb &
      
    - name: Wait for Server
      run: sleep 5 && ps aux | grep Shoppingcart.rb

    - name: Access server
      run: curl http://localhost:4567/checkout
  



      
